### ISSUE TITLE
Setup ATD/LIT Trello Development Board

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-monorepo-testing#165]
### Objective:
Prepare the [ATD/LIT Trello Board](https://trello.com/b/2MZ7yNTv/atd-lit) for Launch IT (LIT).
- Example of a DSD card that went through this development process [here ](https://trello.com/c/oFReYzBl/672-ev-folder-updates)
- Cards need to be ready to pickup by LIT and do the dev with little to no questions for the PM

**Tasks:**

- [x] Add a card for each backlog issue rated priority 1
    * There are six priority 1 issues
- [x] Each card should have a user story
- [ ] Each card should have acceptance criteria

**Misc. Resources:**
- [Backlog Folder ](https://drive.google.com/drive/u/1/folders/1xXp0Hi3M6MEETLaTggPiwKUuXdROBa_o)
- [AMANDA Ops Strategy doc](https://docs.google.com/spreadsheets/d/12djLwekONVUvZRorp_pl4wDxhC8LsU-LV1henIIxOsg/edit?usp=sharing)

*Migrated from [atd-data-tech #1423](https://github.com/cityofaustin/atd-data-tech/issues/1423)*
