### ISSUE TITLE
Stop Archiving Flex Notes from Data Tracker

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-monorepo-testing#174]
We archive flex notes for SR flex notes in the data tracker in our postgrest db. We do this because they create a lot of space in our knack apps, so we delete them periodically from the Knack app and back them up in postgres. This data is always retained in the CSR system, so this is a redundancy.  

However, we have never in the past year needed to retrieve this data. Let's kill this process. 

It's all described here: https://github.com/cityofaustin/atd-knack-data-tracker/wiki/CSR-%7C-Flex-Note-Archiving

TODO:
- [ ] update atd-data-deploy scripts to remove this job
- [ ] deprecate script from atd-data-publishing
- [ ] update wiki
- [ ] update AMD on this change

*Migrated from [atd-data-tech #700](https://github.com/cityofaustin/atd-data-tech/issues/700)*
