### ISSUE TITLE
Project: ROW Attendance Tracking

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-monorepo-testing#281]
## Description
This application will be used to track times and hours worked for the Right-of-Way permit team. This will improve the accuracy of overtime reporting and anticipating wait times for our customers. 

**Submitted via email to Tracy on 7/12/19 by Paloma A-R**

### As a manager I want to be able to track my permit staff's time more closely, so that I can better report on overtime needs and provide customers with a better idea of wait times. 

**Describe the outcome you'd like to see when this feature is implemented.**
Staff will be able to log their arrivals and departures.
I will be able to report more accurately on overtime worked. 
Perhaps we can tie this attendance tracking into our current (KNACK enabled) customer sign-in app, to inform a larger picture out our walk-in customer management. 

**Describe any workarounds you currently have in place or alternative solutions you've considered.**
Currently staff sends me an email when they arrive and leave. Its very difficult to answer questions about time worked using this solution. 

**What else should we know?**
We're considering using an existing CTM solution for this. 

**How would you rate the impact of this issue?**

- [ ] Must have — The application is illegal, unsafe, or not functional without it.
- [X] Should have — This is important but not vital functionality or there is a temporary workaround. 
- [ ] Could have — We want this but there are more important requests. 
- [ ] Unsure

**If it is critical that this feature is delivered by a certain date, when and why?**

*Migrated from [atd-data-tech #357](https://github.com/cityofaustin/atd-data-tech/issues/357)*
