### ISSUE TITLE
User Support: Arthur W Needs LM Permissions in TEST for UAT

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-monorepo-testing#380]
### Overview:
- Arthur W. with ORES has been assigned to UAT for ROWMAN 3 - LM Self Assignment. 
- Melissa T with ORES reported this issue to Tracy L on 2/13/2020 by email

**Tasks**
- [ ] Create AMANDA New User Request Form (NERF) for this update
- [ ] Update permission in TEST
- [ ] Ask Arthur to confirm the permissions update is successful, and meets his requirements

*Migrated from [atd-data-tech #1426](https://github.com/cityofaustin/atd-data-tech/issues/1426)*
