### ISSUE TITLE
Project: DTS Service Delivery

### ISSUE THREAD

**Issue by atdservicebot** [cityofaustin/atd-monorepo-testing#421]
## Description
Design and document processes the DTS team can use to intake, manage, and deliver services.

### Resources
- [Project Folder](https://drive.google.com/drive/u/1/folders/1nAzamPSCveOHjGf2Pj70MFlFOtZitpow)
- [Draft Workflow Diagram](https://www.draw.io/#G1qPEKQG9LyTcbrmIdR7qjlcAEGcJ55y2R)
- [Project Templates](https://drive.google.com/drive/folders/1Sio1YZkUCPoWP5NtZ_oDcfZnoq6zx6f1)
- [Project Overview Presentation](https://docs.google.com/presentation/d/1xlkXrsygvql9YOi_DVKldWdUB2Dm8sYmTure9glm6Bg/edit#slide=id.p)

**Action Items**
- [x] A - Create ~Project Parent~ Epic label
- [x] All - Collaborate on intake form fields #193 
- [x] T - Setup meeting w/ Amenity to keep working on this later this week
- [x] J - [Create issue for Mateo to look at pushing github project info to transportation.austintexas.io](https://github.com/cityofaustin/transportation.austintexas.io/issues/245) 
- [ ] Define 'Triage' and the tasks involved
- [ ] Define which services are 24/7, if any
- [ ] Further define what should happen during 'Review/QA'
    * What does 'User Acceptance Testing', 'Usability Testing' mean to the team?
- [x] Form submission confirmation message (1 for severe issues, 1 for everything else)
- [x] Create a template for the email sent to customers after they submit an issue in the portal
    * All form submission confirmation emails should include some sort of 'What to expect' message to the customer.
    * Link it to the github issue, which can't happen until the issue is assigned to the correct repo
- [x] Figure out how severe issues will be quickly & easily identifiable, both in GH and in the email confirmations
- [x] Make sure that the default status of new GH issues is 'New Issue' - Be sure before implementing new procedures.
- [x] Add a new pipeline for 'Discovery/Scoping'
- [x] John would like work groups to get some type of monthly update on their backlog & the work we're doing for them. #468
- [x] Implement a quarterly department prioritization & collaboration communication. Inform customers of their backlog, among other info to be identified.  #688
- [x]  Test what happens to a GH issue link after the issue is transferred to a new repo.
- [x] Add to project workflow: assign a PM before the ~~intake~~ kickoff meeting. 
- [x] Gather standard discovery meeting questions from John & Diana (questions they want asked at all intake meetings). #469 
- [x] Create some type of formal discovery meeting artifact docs(s). #470

*Migrated from [atd-data-tech #83](https://github.com/cityofaustin/atd-data-tech/issues/83)*
